# fly.toml app configuration file generated for creature-foja on 2024-08-04T17:29:42+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'creature-foja'
primary_region = 'waw'

[build]

[[mounts]]
source = 'foja'
destination = '/data'
initial_size = '1gb'
processes = ['app']

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
max_machines_running = 1

processes = ['app']

[[services]]
protocol = 'tcp'
internal_port = 222

[[services.ports]]
port = 22

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
