openapi: 3.0.0
info:
  title: Forgejo API
  description: |-
    Forgejo REST API

  contact:
    email: contact@forgejo.org
  license:
    name: MIT
    url: https://codeberg.org/forgejo/forgejo/src/branch/forgejo/LICENSE
  version: 1.0.0
externalDocs:
  description: Find out more about Forgejo
  url: http://forgejo.org
servers:
  - url: /api/forgejo/v1
paths:
  /version:
    get:
      summary: API version
      description: Semantic version of the Forgejo API
      operationId: getVersion
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Version'
components:
  schemas:
    Version:
      type: object
      properties:
        version:
          type: string

